### ISSUE TITLE
clock setting options take any value

### ISSUE THREAD

**Issue by pszi1ard** [RadeonOpenCompute/ROC-smi#1]
rocm-smi dose not perform checks on --setsclk value.

```
$ /opt/rocm/bin/rocm-smi -d 0 --setsclk 1

===================   ROCm System Management Interface   ===================
GPU[0]          : Successfully set GPU Clock frequency to Level 1
===================          End of ROCm SMI Log         ===================

$ /opt/rocm/bin/rocm-smi -d 0 --setsclk 2

===================   ROCm System Management Interface   ===================
GPU[0]          : Successfully set GPU Clock frequency to Level 2
===================          End of ROCm SMI Log         ===================

$ /opt/rocm/bin/rocm-smi -d 0 --setsclk 100000

===================   ROCm System Management Interface   ===================
GPU[0]          : Successfully set GPU Clock frequency to Level 100000
===================          End of ROCm SMI Log
```

Device used is Fiji.

Ref: https://github.com/RadeonOpenCompute/ROCm/issues/90

**Comment by gstoner** [comment]
What are you trying to do.

Greg
On Feb 24, 2017, at 2:33 PM, Szilárd Páll <notifications@github.com<mailto:notifications@github.com>> wrote:


rocm-smi dose not perform checks on --setsclk value.

$ /opt/rocm/bin/rocm-smi -d 0 --setsclk 1

===================   ROCm System Management Interface   ===================
GPU[0]          : Successfully set GPU Clock frequency to Level 1
===================          End of ROCm SMI Log         ===================

$ /opt/rocm/bin/rocm-smi -d 0 --setsclk 2

===================   ROCm System Management Interface   ===================
GPU[0]          : Successfully set GPU Clock frequency to Level 2
===================          End of ROCm SMI Log         ===================

$ /opt/rocm/bin/rocm-smi -d 0 --setsclk 100000

===================   ROCm System Management Interface   ===================
GPU[0]          : Successfully set GPU Clock frequency to Level 100000
===================          End of ROCm SMI Log


Device used is Fiji.

Ref: RadeonOpenCompute/ROCm#90<https://github.com/RadeonOpenCompute/ROCm/issues/90>

**Comment by pszi1ard** [comment]
> What are you trying to do.

Trying to set the clock on a Fiji GPU which would not clock up. I first thought --setsclk takes as argument a frequency value, realizing only later that it's the "Level" that should be passed. At least two things are off:
* invalid level values should not be accepted
* invalid level values should not result in success, i.e. ```Successfully set GPU Clock frequency to Level 1000```

**Comment by kentrussell** [comment]
This is a little misleading. The values that are passed in are a mask. The kernel then parses the mask accordingly.
For example: Let's say that you have 7 performance levels. You can mask it to use levels 1, 4, 5 and 6 with --setclk 1456 . 
Passing 1000 technically just sets it to level 1. I'll update the documentation in the next release, and try to add a parser to check that the input is somewhat sane.

**Comment by pszi1ard** [comment]
@kentrussell Indeed, it's _rather_ misleading. Now I realize the only cue to the fact that multiple levels can be enabled is the plural in "Level(s)" in the message. Please do clarify this. Actually, I'd very much like to see docs much more docs, including man pages.

Slightly OT, but back to my original issue: what does it mean that my Fiji device does not clock up from the 300 MHz base _ever_, regardless of what I set in ```--setperflevel```, ```--setslck``` or even ```--setoverdrive```?

**Comment by kentrussell** [comment]
I agree. For the 1.5 release, we'll try to explain the functionality a bit better all-around. 

Just for my own reference, give this a shot and paste the output (I want to see if the appropriate sysfs values are changing properly):
roc-smi -a
roc-smi --setsclk 7
roc-smi -a

**Comment by pszi1ard** [comment]
@kentrussell For the sake of consistency and to stay on topic, I posted the output on the linked issue where I originally reported this behavior. I hope you don't mind.

Do you want me to reword this issue and broaden its scope to an RFE for more docs?

**Comment by kentrussell** [comment]
Ugh sorry, typo on my part. It should've been
/opt/rocm/bin/rocm-smi -a
/opt/rocm/bin/rocm-smi --setsclk 7
/opt/rocm/bin/rocm-smi -a

Thanks again.  And the more we have this documented, the better.

**Comment by pszi1ard** [comment]
@kentrussell No problem, the outputs are here: https://github.com/RadeonOpenCompute/ROCm/issues/90#issuecomment-282804867

**Comment by kentrussell** [comment]
Hi @pszi1ard 
Can you give it a try with the new 1.5 release?

**Comment by pszi1ard** [comment]
The deb repository doesn't seem to have 1.5 packages yet (is the release still pending?). I'd prefer to not build from sources, but use binaries.

**Comment by jedwards-AMD** [comment]
The binaries will be uploaded today.

**Comment by pszi1ard** [comment]
I've just tried the 1.6 release and the command line messages have certainly improved. However, the return value is still not set correctly and as a *nix shell application this is definitely not great:

```
$ sudo /opt/rocm/bin/rocm-smi -d 0 --setsclk 100000 && echo "-> success :)" || echo "-> fail :("


====================    ROCm System Management Interface    ====================
GPU[0] 		: Unable to set clock to unsupported Level - Max Level is 7
====================           End of ROCm SMI Log          ====================

-> success :)
```

**Comment by kentrussell** [comment]
The difficult edge-case here would be:

$ sudo /opt/rocm/bin/rocm-smi --setsclk 8 && echo "-> success :)" || echo "-> fail :("


====================    ROCm System Management Interface    ====================
GPU[0] 		: Unable to set clock to unsupported Level - Max Level is 7
GPU[1] 		: Successfully set GPU Clock frequency mask to Level 8
====================           End of ROCm SMI Log          ====================

success|fail?

We can definitely look into throwing some proper return codes when things go awry, but it's harder to generalize when we support setting multiple values for multiple GPUs in the same command. Still, it could be something that we can work on.

**Comment by pszi1ard** [comment]
I understand that, when a tool does multiple things at a time, it may not always be obvious what the return code should be. Still, it sees to be a matter of deciding which classes or unsuccessful operations you treat as errors; it's probably a good idea to also make that explicit, e.g. in your above example, it's not hard to miss the fact that for GPU[0] --setsclk failed -- a "WARNING" prefix would help (if you want to treat this as non error).

**Comment by kentrussell** [comment]
Even something like a warning at the end saying that some commands failed would be more useful than what is currently displayed. Especially when doing a few things at once, you might not think about scrolling up to analyze each statement for each GPU. It's something that we can work on, though. Thanks for the input!

**Comment by kentrussell** [comment]
With 1.6.1, we should hopefully have clarified any issue with any bad values given. How's it look on your end, @pszi1ard ?

**Comment by pszi1ard** [comment]
@kentrussell not sure what change should I see in the latest release? It still gives a zero return value when setting clocks fails.

Additionally, I just noticed that e.g. the `rocm-smi -a` mixes info from multiple devices. I think this output is confusing and IMO it would be better to either list per-device (if very important, potentially allow interleaved output with an option).

**Comment by kentrussell** [comment]
I've done a big rework (sorry for the delay, it took a while to get it done). Can you give it a shot with the release on the krussell/fixes branch? I did a big rework for 1.7 and there were a couple bugs that I didn't get taken care of in time. If the krussell/fixes version works, then great, but if there's anything else that's going awry, please let me know!

**Comment by kentrussell** [comment]
Can you try it out with the 1.7.1 release that just came out?

**Comment by pszi1ard** [comment]
Thanks for the feedback! I'll try it out as soon as I get the 1.7.1 update, but I see nothing in the deb repos. Is it supposed to be out already?

**Comment by kentrussell** [comment]
The repos should be updated this week. It's a lot quicker for me to push the code here for three projects (SMI, ROCT, ROCK) than it is for the packaging team to get the repos updated for every ROCm project. It should be coming by mid-week, barring any setbacks.

**Comment by gstoner** [comment]
We working on rolling it out either  today or Tuesday.  I need to do one last assessment on two libraries.


G

On Mar 5, 2018, at 7:38 AM, Szilárd Páll <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the feedback! I'll try it out as soon as I get the 1.7.1 update, but I see nothing in the deb repos. Is it supposed to be out already?

**Comment by kentrussell** [comment]
Closing this for now. Please feel free to re-open it if it's still occurring on 1.8

**Comment by pszi1ard** [comment]
It behaves much better, thanks for the improvements.
