### ISSUE TITLE
question: problems in interpreting the results

### ISSUE THREAD

**Issue by damnms** [RadeonOpenCompute/ROC-smi#100]
hi, i'd like to see if i am also affected by this problem with the extrem high idle power usage of the new 7900 xt/xtx cards.

when i run rocm-smi i get:

```
========================ROCm System Management Interface========================
================================================================================
GPU  Temp   AvgPwr  SCLK    MCLK     Fan    Perf  PwrCap  VRAM%  GPU%  
0    42.0c  39.02W  600Mhz  2700Mhz  None%  auto  N/A       5%   0%    
1    50.0c  89.0W   27Mhz   1249Mhz  29.8%  auto  315.0W    3%   3%    
================================================================================
==============================End of ROCm SMI Log ==============================

```

unfortunately, i dont know why it shows 2 gpus. there was a guess that one is the igpu. i believe my system is eating 140w in idle (yay, no heater required anymore). 

when i use --show-hw
```
========================ROCm System Management Interface========================
================================================================================
GPU  DID   GFX RAS  SDMA RAS  UMC RAS  VBIOS            BUS           
0    164e  N/A      N/A       N/A      102-RAPHAEL-008  0000:12:00.0  
1    744c  N/A      N/A       N/A      115-D702BS0-101  0000:03:00.0  
==============================End of ROCm SMI Log ==============================

```
that really looks like 0 is the igpu and 1 is the 7900xtx.
can someone confirm that my assumptions/findings are correct?
and offtopic: can i disable the igpu? i see no reason why this runs with 40w and does nothing because nothing is connected to it.

**Comment by jlgreathouse** [comment]
Hi @damnms please note that this repository is deprecated, as per the README.md at https://github.com/RadeonOpenCompute/ROC-smi/blob/master/README.md.

That said, yes, GPU 0 is your iGPU. It's potentially possible to disable it in your BIOS -- it depends on your motherboard.
