### ISSUE TITLE
Is there a way to reset fan to default?

### ISSUE THREAD

**Issue by newling** [RadeonOpenCompute/ROC-smi#11]
i.e. an equivalent to --resetclocks for the fan?

**Comment by ratbuddy** [comment]
I'd like to know this as well. According to https://github.com/RadeonOpenCompute/ROC-smi/issues/8 it was added, but using the most recent version from the apt repo, that feature is not implemented yet.

**Comment by gstoner** [comment]
I am checking in on this.

**Comment by ratbuddy** [comment]
Any news?

**Comment by calvintam236** [comment]
I think this is necessary feature too. I don't want to reboot the system just to reset the fan.

@gstoner any updates?

**Comment by gstoner** [comment]
This will get fixed in the next release, I see if we do a mid-term release of ROCm-smi

**Comment by kentrussell** [comment]
Technically there isn't a "default fan" option. The default is set by the GPU and we don't have a call to get that from the PP tables. It's something that we can try to integrate in a future release, but the easiest way to handle it is to just set the fan to 35 (this is the normal default for a normal fan-cooled Fiji/Vega10). When the temperature requires it, it will manually override the fan settings and once that happens once, it should go back to the normal method of increasing/decreasing based on GPU temperature.

**Comment by kentrussell** [comment]
Turns out I was wrong, and the solution was implemented by @mathewhall . I managed to miss the commit in the 1.7 release but I should have that addressed soon. You can refer to https://github.com/RadeonOpenCompute/ROC-smi/pull/9 for help on it though!

**Comment by kentrussell** [comment]
I'll post here to clarify, just in case anyone is reading this as well. The fan's won't get bumped back to automatic unless the user specifies it, regardless of the GPU temperature or state. The driver doesn't have any functionality in it to force clocks to auto if the GPU gets too hot. Sorry for any confusion that I may have caused there!
