### ISSUE TITLE
Persistence mode

### ISSUE THREAD

**Issue by calvintam236** [RadeonOpenCompute/ROC-smi#13]
I know `nvidia-smi` offer it. I would like to see `rocm-smi` getting this feature. Is there a plan for this?

**Comment by kentrussell** [comment]
This would need to be implemented in the kernel. rocm-smi is merely a tool to call into the kernel, similar to nvidia-smi. If you want a persistence mode, it would need to be implemented in the kernel itself (https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver). Once it's there, the SMI can call it
