### ISSUE TITLE
Power consumption is N/A

### ISSUE THREAD

**Issue by withchandra** [RadeonOpenCompute/ROC-smi#16]
Hello, I tried to install all requirements for roc-smi to be working properly, however I cannot get the power consumption data. (other data is okay)

Result when I do **sudo ./rocm-smi**

>====================    ROCm System Management Interface    ====================
>GPU  Temp    AvgPwr   SCLK     MCLK     Fan      Perf    SCLK OD
>  0   50.0c   N/A      1150Mhz  2100Mhz  47.84%   manual    0%       
> 1   52.0c   N/A      1150Mhz  2100Mhz  47.84%   manual    0%       
> 2   55.0c   N/A      1150Mhz  2100Mhz  47.84%   manual    0%       
> 3   54.0c   N/A      1150Mhz  2100Mhz  47.84%   manual    0%       
> ====================           End of ROCm SMI Log          ====================

I am currently running 
- Ubuntu Server 16.04 LTS
- AMDGPUPRO Driver version 17.40
- I did install rocm using below command

```
wget -qO - http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key | sudo apt-key add -
sudo sh -c 'echo deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ xenial main > /etc/apt/sources.list.d/rocm.list'
```
```
sudo apt-get update
sudo apt-get install rocm-dkms rocm-opencl-dev
sudo apt install -y rocm-amdgpu-pro
echo 'export LLVM_BIN=/opt/amdgpu-pro/bin' | sudo tee /etc/profile.d/amdgpu-pro.sh
```
```
sudo usermod -a -G video $LOGNAME
```

if I checked using ***uname -r*** the result is
```
4.4.0-104-generic
```

Did I miss something? My friend told me that I missed installing the kfd kernel, but I could not find a good tutorial / guide for that. Thank you.

**Comment by kentrussell** [comment]
The GPU usage comes from a Kernel SysFS file. If the file isn't there, it won't be loaded. And I am unsure if the AMDGPU PRO branch has the GPU usage as part of its debugfs file. To find out, try this (since the SMI just reads the sysfs file and parses the results):
sudo su
cat /sys/kernel/debug/dri/*/amdgpu_pm_info  (NOTE: You may need to do a different number than 0 depending on what GPUs are in use on your system)
If the file isn't there, or if it just doesn't include the "average GPU" string, then the AMDGPU PRO driver doesn't support it, and you'll need to use the ROCm kernel . To install the ROCm DKMS package (which will replace AMDGPU PRO), follow the instructions at https://github.com/RadeonOpenCompute/ROCm/wiki . Good luck!

**Comment by withchandra** [comment]
Thank you for the answer, I have followed you and execute this command:
`cat /sys/kernel/debug/dri/*/amdgpu_pm_info` 

The result show the average GPU Power consumption (in watt) - attached below.
But when I run the ./rocm-smi the column AvgPwr still N/A.

```
Clock Gating Flags Mask: 0x37bcf
	Graphics Medium Grain Clock Gating: On
	Graphics Medium Grain memory Light Sleep: On
	Graphics Coarse Grain Clock Gating: On
	Graphics Coarse Grain memory Light Sleep: On
	Graphics Coarse Grain Tree Shader Clock Gating: Off
	Graphics Coarse Grain Tree Shader Light Sleep: Off
	Graphics Command Processor Light Sleep: On
	Graphics Run List Controller Light Sleep: On
	Graphics 3D Coarse Grain Clock Gating: Off
	Graphics 3D Coarse Grain memory Light Sleep: Off
	Memory Controller Light Sleep: On
	Memory Controller Medium Grain Clock Gating: On
	System Direct Memory Access Light Sleep: Off
	System Direct Memory Access Medium Grain Clock Gating: On
	Bus Interface Medium Grain Clock Gating: Off
	Bus Interface Light Sleep: On
	Unified Video Decoder Medium Grain Clock Gating: On
	Video Compression Engine Medium Grain Clock Gating: On
	Host Data Path Light Sleep: Off
	Host Data Path Medium Grain Clock Gating: On
	Digital Right Management Medium Grain Clock Gating: Off
	Digital Right Management Light Sleep: Off
	Rom Medium Grain Clock Gating: On
	Data Fabric Medium Grain Clock Gating: Off

GFX Clocks and Power:
	2100 MHz (MCLK)
	1150 MHz (SCLK)
	68.49 W (VDDC)
	16.0 W (VDDCI)
	97.32 W (max GPU)
	96.151 W (average GPU)

GPU Temperature: 51 C
GPU Load: 100 %

UVD: Disabled

VCE: Disabled
Clock Gating Flags Mask: 0x37bcf
	Graphics Medium Grain Clock Gating: On
	Graphics Medium Grain memory Light Sleep: On
	Graphics Coarse Grain Clock Gating: On
	Graphics Coarse Grain memory Light Sleep: On
	Graphics Coarse Grain Tree Shader Clock Gating: Off
	Graphics Coarse Grain Tree Shader Light Sleep: Off
	Graphics Command Processor Light Sleep: On
	Graphics Run List Controller Light Sleep: On
	Graphics 3D Coarse Grain Clock Gating: Off
	Graphics 3D Coarse Grain memory Light Sleep: Off
	Memory Controller Light Sleep: On
	Memory Controller Medium Grain Clock Gating: On
	System Direct Memory Access Light Sleep: Off
	System Direct Memory Access Medium Grain Clock Gating: On
	Bus Interface Medium Grain Clock Gating: Off
	Bus Interface Light Sleep: On
	Unified Video Decoder Medium Grain Clock Gating: On
	Video Compression Engine Medium Grain Clock Gating: On
	Host Data Path Light Sleep: Off
	Host Data Path Medium Grain Clock Gating: On
	Digital Right Management Medium Grain Clock Gating: Off
	Digital Right Management Light Sleep: Off
	Rom Medium Grain Clock Gating: On
	Data Fabric Medium Grain Clock Gating: Off

GFX Clocks and Power:
	2100 MHz (MCLK)
	1150 MHz (SCLK)
	74.89 W (VDDC)
	16.0 W (VDDCI)
	102.123 W (max GPU)
	102.191 W (average GPU)

GPU Temperature: 53 C
GPU Load: 100 %

UVD: Disabled

VCE: Disabled
Clock Gating Flags Mask: 0x37bcf
	Graphics Medium Grain Clock Gating: On
	Graphics Medium Grain memory Light Sleep: On
	Graphics Coarse Grain Clock Gating: On
	Graphics Coarse Grain memory Light Sleep: On
	Graphics Coarse Grain Tree Shader Clock Gating: Off
	Graphics Coarse Grain Tree Shader Light Sleep: Off
	Graphics Command Processor Light Sleep: On
	Graphics Run List Controller Light Sleep: On
	Graphics 3D Coarse Grain Clock Gating: Off
	Graphics 3D Coarse Grain memory Light Sleep: Off
	Memory Controller Light Sleep: On
	Memory Controller Medium Grain Clock Gating: On
	System Direct Memory Access Light Sleep: Off
	System Direct Memory Access Medium Grain Clock Gating: On
	Bus Interface Medium Grain Clock Gating: Off
	Bus Interface Light Sleep: On
	Unified Video Decoder Medium Grain Clock Gating: On
	Video Compression Engine Medium Grain Clock Gating: On
	Host Data Path Light Sleep: Off
	Host Data Path Medium Grain Clock Gating: On
	Digital Right Management Medium Grain Clock Gating: Off
	Digital Right Management Light Sleep: Off
	Rom Medium Grain Clock Gating: On
	Data Fabric Medium Grain Clock Gating: Off

GFX Clocks and Power:
	2100 MHz (MCLK)
	1150 MHz (SCLK)
	68.119 W (VDDC)
	16.0 W (VDDCI)
	96.103 W (max GPU)
	96.221 W (average GPU)

GPU Temperature: 55 C
GPU Load: 100 %

UVD: Disabled

VCE: Disabled
Clock Gating Flags Mask: 0x37bcf
	Graphics Medium Grain Clock Gating: On
	Graphics Medium Grain memory Light Sleep: On
	Graphics Coarse Grain Clock Gating: On
	Graphics Coarse Grain memory Light Sleep: On
	Graphics Coarse Grain Tree Shader Clock Gating: Off
	Graphics Coarse Grain Tree Shader Light Sleep: Off
	Graphics Command Processor Light Sleep: On
	Graphics Run List Controller Light Sleep: On
	Graphics 3D Coarse Grain Clock Gating: Off
	Graphics 3D Coarse Grain memory Light Sleep: Off
	Memory Controller Light Sleep: On
	Memory Controller Medium Grain Clock Gating: On
	System Direct Memory Access Light Sleep: Off
	System Direct Memory Access Medium Grain Clock Gating: On
	Bus Interface Medium Grain Clock Gating: Off
	Bus Interface Light Sleep: On
	Unified Video Decoder Medium Grain Clock Gating: On
	Video Compression Engine Medium Grain Clock Gating: On
	Host Data Path Light Sleep: Off
	Host Data Path Medium Grain Clock Gating: On
	Digital Right Management Medium Grain Clock Gating: Off
	Digital Right Management Light Sleep: Off
	Rom Medium Grain Clock Gating: On
	Data Fabric Medium Grain Clock Gating: Off

GFX Clocks and Power:
	2100 MHz (MCLK)
	1150 MHz (SCLK)
	64.156 W (VDDC)
	16.0 W (VDDCI)
	92.94 W (max GPU)
	93.2 W (average GPU)

GPU Temperature: 54 C
GPU Load: 100 %

UVD: Disabled

VCE: Disabled
```

It shows the average GPU Power.. it would be nice if I can see it from ./rocm-smi command. 
meanwhile I will use this command to check the power consumption..

**Comment by kentrussell** [comment]
Ugh this is something that I saw previously in RHEL for one of the other teams here. The SMI assumes that the DebugFS file "name" reports the PCI device, and that's how we correlate the DRM device to the HW Monitor and the Kernel DebugFS node. Unfortunately that file wasn't being populated in RHEL and I couldn't find out why, which is likely what's happening in your situation too. I was working on a different method for correlating devices together but haven't come up with a working solution yet. For now, you'll be stuck running the cat instead of using the SMI, but it's something that I am actively working on right now and can hopefully get into our next release

**Comment by withchandra** [comment]
Thank you very much for your hard work. 

I will patiently waiting for the next release 👍 Good luck with the project. 
And again, thank you!

**Comment by reqshark** [comment]
encountering same on my ubuntu

while we're on this topic, I have a blatant feature request:

* to tune GPU voltage (mV)
  * to get/set values along millivolt scale mapped to clock frequency ramps for memory and GPU

if you were open to exposing that level of the GPU power management, do you think it would go with the compute profile/setprofile command arguments/list, or as a new `--setpower` list of values for memory and gpu?

**Comment by preda** [comment]
See also:
https://github.com/RadeonOpenCompute/ROCm/issues/305

This is a regression in the script itself.

**Comment by kentrussell** [comment]
It's not a regression in the script itself, but a result of making assumptions about the contents of a debugfs file that is not always being populated. I have a fix that I am testing internally and will push either for 1.7, or will push to krussell/fixes if the deadline gets missed. It works on all platform combinations that I have tried (the only one that I haven't tried is Intel Integrated GPU + nVidia GPU + AMD GPU, but it should work since I took out some assumptions)

**Comment by kentrussell** [comment]
Can you try it out with the 1.7.1 release that just came out?

**Comment by kentrussell** [comment]
Assuming that it's fine since I haven't heard back in 2 months
