### ISSUE TITLE
roc-smi --setoverdrive %

### ISSUE THREAD

**Issue by TaiPhamD** [RadeonOpenCompute/ROC-smi#17]
--setoverdrive %             Set GPU OverDrive level (manual|high)

Is there a way to make this setting available to overdrive memory clock as well and not just GPU clock?

**Comment by kentrussell** [comment]
Unfortunately OverDrive is only available for SCLK (GPU Clock) and is not supported for Memory Clocks at this time. I haven't heard anything regarding whether this will be supported later, but it's definitely not something that is currently supported or implemented. Sorry!
