### ISSUE TITLE
rocm-smi + Vega 64

### ISSUE THREAD

**Issue by rjfnobre** [RadeonOpenCompute/ROC-smi#22]
I tried with a negative value for 'pp_sclk_od' thinking it would result in underclocking the GPU (at least power level 7).

echo "-2" | sudo tee /sys/class/drm/card0/device/pp_sclk_od

But the result was overclocking the power level 7 of the GPU to 2400MHz (this is what 'rocm-smi -a' reported) , which resulted in an immediate crash, as the GPU is obviously not able to sustain such high clock.

Is this what is expected to happen?

I suppose the Vega 64 graphics card itself has protections to avoid malfunctioning (or incorrect use) of the drivers causing damage to its hardware.

Anyway, what I'm trying to accomplish, is using low GPU clocks (power level 1: 991MHz would suffice) while at the same time using overclocked HBM2.

In order to try to accomplish this I overclocked the memory using the overdrive configuration file as follows:
echo "11" | sudo tee /sys/class/drm/card0/device/pp_mclk_od

Then I set GPU power mode to 1.
rocm-smi -d 0 --setsclk 1

And the HBM2 power level to 3 (the highest power level).
rocm-smi -d 0 --setmclk 3

Unfortunately, the last commands seems to not work if the HBM2 was previously overclocked, unless the power level of the GPU is 6 or 7.
If the GPU is set to power levels below 6, then the HBM2 becomes fixed at 500MHz (memory power level 1).
Why is this?

Trying to downclock the GPU at power level 7 was a desperate (and failed) attempt to achieve low GPU clocks + overclocked HBM2.

In addition, I would like to know if it is posssible to undervolt the GPU with ROC-smi.

**Comment by kentrussell** [comment]
I'll try to cover a few things:
1) Echoing an invalid value to sysfs should have resulted in an error saying "Invalid argument" since it's not a number. But a negative value isn't an invalid input (https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/blob/master/drivers/gpu/drm/amd/amdgpu/amdgpu_pm.c#L401) . There may be a use case where the user wants the top level, so they can set the mask to -1 . I am talking with some of the other kernel guys to see if it's an oversight or a valid usecase.
2) Can you post the outputs of the following commands (I'll try to work on adding an option to update mclk OD, since I didn't do that yet)? Thanks
rocm-smi -d 0 -a
echo "11" | sudo tee /sys/class/drm/card0/device/pp_mclk_od
rocm-smi -d 0 --setsclk 1
rocm-smi -d 0 --setmclk 3
rocm-smi -d 0 -a

Thanks!

**Comment by rjfnobre** [comment]
$rocm-smi -d 0 -a
....................    ROCm System Management Interface    ....................
................................................................................
GPU[0] 		: GPU ID: 0x687f
................................................................................
................................................................................
GPU[0] 		: Temperature: 81.0c
................................................................................
................................................................................
GPU[0] 		: GPU Clock Level: 1 (991Mhz)
GPU[0] 		: GPU Memory Clock Level: 3 (945Mhz)
................................................................................
................................................................................
GPU[0] 		: Fan Level: 124 (48.63)%
................................................................................
................................................................................
GPU[0] 		: Current PowerPlay Level: manual
................................................................................
................................................................................
GPU[0] 		: Current OverDrive value: 0%
................................................................................
................................................................................
GPU[0] 		: Minimum SCLK: 1536MHz
GPU[0] 		: Minimum MCLK: 0MHz
GPU[0] 		: Activity threshold: 0%
GPU[0] 		: Hysteresis Up: 0ms
GPU[0] 		: Hysteresis Down: 0ms
................................................................................
................................................................................
GPU[0] 		: Cannot get GPU power Consumption: Average GPU Power not supported
................................................................................
................................................................................
GPU[0] 		: Supported GPU clock frequencies on GPU0
GPU[0] 		: 0: 852Mhz 
GPU[0] 		: 1: 991Mhz *
GPU[0] 		: 2: 1084Mhz 
GPU[0] 		: 3: 1138Mhz 
GPU[0] 		: 4: 1200Mhz 
GPU[0] 		: 5: 1401Mhz 
GPU[0] 		: 6: 1536Mhz 
GPU[0] 		: 7: 1630Mhz 
GPU[0] 		: 
GPU[0] 		: Supported GPU Memory clock frequencies on GPU0
GPU[0] 		: 0: 167Mhz 
GPU[0] 		: 1: 500Mhz 
GPU[0] 		: 2: 800Mhz 
GPU[0] 		: 3: 945Mhz *
GPU[0] 		: 
................................................................................
....................           End of ROCm SMI Log          ....................


$echo "11" | sudo tee /sys/class/drm/card0/device/pp_mclk_od
$rocm-smi -d 0 --setsclk 1
$rocm-smi -d 0 --setmclk 3
$rocm-smi -d 0 -a
....................    ROCm System Management Interface    ....................
................................................................................
GPU[0] 		: GPU ID: 0x687f
................................................................................
................................................................................
GPU[0] 		: Temperature: 66.0c
................................................................................
................................................................................
GPU[0] 		: GPU Clock Level: 1 (991Mhz)
GPU[0] 		: GPU Memory Clock Level: 3 (1048Mhz)
................................................................................
................................................................................
GPU[0] 		: Fan Level: 124 (48.63)%
................................................................................
................................................................................
GPU[0] 		: Current PowerPlay Level: manual
................................................................................
................................................................................
GPU[0] 		: Current OverDrive value: 0%
................................................................................
................................................................................
GPU[0] 		: Minimum SCLK: 1536MHz
GPU[0] 		: Minimum MCLK: 0MHz
GPU[0] 		: Activity threshold: 0%
GPU[0] 		: Hysteresis Up: 0ms
GPU[0] 		: Hysteresis Down: 0ms
................................................................................
................................................................................
GPU[0] 		: Cannot get GPU power Consumption: Average GPU Power not supported
................................................................................
................................................................................
GPU[0] 		: Supported GPU clock frequencies on GPU0
GPU[0] 		: 0: 852Mhz 
GPU[0] 		: 1: 991Mhz *
GPU[0] 		: 2: 1084Mhz 
GPU[0] 		: 3: 1138Mhz 
GPU[0] 		: 4: 1200Mhz 
GPU[0] 		: 5: 1401Mhz 
GPU[0] 		: 6: 1536Mhz 
GPU[0] 		: 7: 1630Mhz 
GPU[0] 		: 
GPU[0] 		: Supported GPU Memory clock frequencies on GPU0
GPU[0] 		: 0: 167Mhz 
GPU[0] 		: 1: 500Mhz 
GPU[0] 		: 2: 800Mhz 
GPU[0] 		: 3: 1048Mhz *
GPU[0] 		: 
................................................................................
....................           End of ROCm SMI Log          ....................



Thanks!!!

**Comment by gstoner** [comment]
Your Temp is too high above at  92 Degrees,  You need to turn the fan on sooner. 

Greg

**Comment by rjfnobre** [comment]
I just noticed that, so I edited my answer above.

Thanks!

**Comment by kentrussell** [comment]
I realize now that I didn't actually put a fix for negative values in the kernel. Basically it just rolls over to the unsigned int, so you're trying to set it to a massive int, so the SMU just says "OK, highest level, done" . How are things looking with the 1.8 kernel and SMI?

**Comment by kentrussell** [comment]
Closing this for now. Please feel free to re-open it if it's still occurring on 1.8
