### ISSUE TITLE
Intel on-board card and rocm-smi output

### ISSUE THREAD

**Issue by sergeimonakhov** [RadeonOpenCompute/ROC-smi#26]
hi i have, intel on-board card and radeon r9 390x, i get command: 
```
rocm-smi -t

====================    ROCm System Management Interface    ====================
================================================================================
GPU[0] 		: Unable to display temperature
GPU[1] 		: Temperature: 74.0c
```
how skip intel card? in output?

**Comment by kentrussell** [comment]
I am hoping to fix this some time in the future, but CPU nodes can be useful for certain critical information for ROCm (as they can be used as well as GPUs). If you don't want to see it, just use the "-d 1" flag to only specify device 1.
