### ISSUE TITLE
room-smi --showvbios

### ISSUE THREAD

**Issue by sergeimonakhov** [RadeonOpenCompute/ROC-smi#27]
i get error:
```
====================    ROCm System Management Interface    ====================
================================================================================
Traceback (most recent call last):
  File "/usr/local/bin/rocm-smi", line 1082, in <module>
    showVbiosVersion(deviceList)
  File "/usr/local/bin/rocm-smi", line 467, in showVbiosVersion
    printLog(device, 'VBIOS version: ' + getSysfsValue(device, 'vbios'))
TypeError: must be str, not NoneType
```
on radeon R9 390x

**Comment by kentrussell** [comment]
That error indicates that there is no device in the device list. What does rocm-smi display with no arguments?

**Comment by kentrussell** [comment]
Assuming that it's fine since I haven't heard back in a month

**Comment by Mcirino** [comment]
Hi, I am also getting this error. I have 4 GPUs, so it looks like rocm-smi is trying to read vBIOS for the CPU device. 
Would it be possible to add a check for if the return value from getSysfsValue(device, 'vbios') is None?

> GPU[3]          : VBIOS version: ##
> GPU[1]          : VBIOS version: ##
> GPU[4]          : VBIOS version: ##
> GPU[2]          : VBIOS version: ##
> Traceback (most recent call last):
>   File "/opt/rocm/bin/rocm-smi", line 1092, in <module>
>     showVbiosVersion(deviceList)
>   File "/opt/rocm/bin/rocm-smi", line 428, in showVbiosVersion
>     printLog(device, 'VBIOS version: ' + getSysfsValue(device, 'vbios'))
> TypeError: Can't convert 'NoneType' object to str implicitly

**Comment by kentrussell** [comment]
I'm working through a bunch of SMI fixes right now, so I'll add this to the list. It's currently being reviewed internally and should make the next release.

**Comment by kentrussell** [comment]
I have a fix for this in the internal 1.9 branch. Once we release 1.9, it will be addressed. Thanks for bringing this back up!

**Comment by kentrussell** [comment]
Unfortunately I missed the cutoff for 1.9.0, so it looks like this will be waiting for the 1.9.1 release.

**Comment by kentrussell** [comment]
I'll close this for now. If there's an issue we can reopen it
