### ISSUE TITLE
Voltage control on Polaris?

### ISSUE THREAD

**Issue by HenryNguyen5** [RadeonOpenCompute/ROC-smi#3]
Is there any plan to introduce voltage control (undervolt/overvolt on core) for Polaris 10 cards?

**Comment by kentrussell** [comment]
@HenryNguyen5 
Sorry for the delay, I was checking to see if this would be included for this 1.5 release. I was told that we do not have a plan to introduce direct voltage control over the GPU, as we will use the PowerPlay tables to determine the proper voltages based on workload and sclk frequency.
