### ISSUE TITLE
Temperature readings don't seem right

### ISSUE THREAD

**Issue by kruftindustries** [RadeonOpenCompute/ROC-smi#30]
Using rocm-smi version 1.7 precompiled from the http://repo.radeon.com/rocm/apt/debian/ xenial repo gives weird temperature readings that are different than they were previously. 6 Frontier edition cards

**Comment by kruftindustries** [comment]
My mistake, this looks line an issue with hwmon.

**Comment by kentrussell** [comment]
Starting in 1.7, the kernel reported temperatures from a different sensor specifically on Vega10. Previously it used "hotspot", which is the hottest reading from any of the sensors. This was changed to "edge" which is  consistent with the rest of the ASICs. You can see the change at https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/commit/e56b8589fec6db8620cded04338a5cd73bc27c7f . That also may have contributed to the temperature change.
