### ISSUE TITLE
rocm-smi has undefined message after monitor as every seconds

### ISSUE THREAD

**Issue by heero-yuy** [RadeonOpenCompute/ROC-smi#31]
Hi,

After monitor the ROCM-smi with GPU activity tracking, found the amdgpu will return a message with "Powerplay", and the ROCm-smi isn't responded at all, I've installed 8 pcs of Radeon Vega64 on Host, with Ubuntu 16.04.4 & Kernel 4.13.0-41, but the problem didn't occurred on ROCm 1.7.1, how can I solve this problem? 

Message : amdgpu : [powerplay] Failed to send message: 0x26 , ret value : 0x0

**Comment by kentrussell** [comment]
So you did the same commands on the 1.7.1 release with the 1.7.1 kernel and 1.7.1 SMI and it was fine, but now you see this with the 1.8.0 kernel and 1.8.0 SMI? The error message indicates that it couldn't get the UclkIndex (PPSMC_MSG_GetCurrentUclkIndex= 0x26 ; which is getting the Memory Clock settings). And does the error only occur when you use the SMI, or does it also occur when you do "cat /sys/class/drm/card0/device/pp_dpm_mclk"? Is there one specific SMI command that you use? And does it happen immediately, or only after a certain number of calls?

**Comment by heero-yuy** [comment]
Hi Kent,

Thanks! The reproduce method is just "watch -n 1 /opt/rocm/bin/rocm-smi", please remind me that the command isn't suitable with much more frequency,
I've checked that the ROCm 1.7.1 didn't found this problem compared to ROCm 1.8.0.
The error only occurred on certain number of rocm-smi calls, and the error is gone when restarting the "watch -n 1 /opt/rocm/bin/rocm-smi" once
the Error can't be found by "cat /sys/class/drm/card0/device/pp_dpm_mclk"
Anything need be welcome to discuss, thanks again!

**Comment by kentrussell** [comment]
There were a decent number of changes made to the mclk settings between 1.7 and 1.8 in the kernel, which I think is the source of this issue. Is there something specific that you're trying to monitor via the SMI? And the last thing to check would be to try the 1.7.2 kernel with the 1.8 SMI, since I am pretty sure that this is an issue with the kernel itself, and not the SMI, due to that error that you originally posted.

**Comment by kentrussell** [comment]
Closing this for now. Please feel free to re-open it if it's still occurring on 1.8.1, but it definitely points to  a change in the kernel, not in the SMI. You're constantly reading a sysfs file that's not designed to be monitored that often. There would need to be a kernel change to address this.
