### ISSUE TITLE
How to  under-volt VEGA cards ? no option for that ! 

### ISSUE THREAD

**Issue by prasoon232** [RadeonOpenCompute/ROC-smi#33]
Hi for new VEGA cards , need  under-volt  option ,please introduce if you can !

**Comment by kentrussell** [comment]
The recent voltage changes are still reasonably new to me, so I don't know if there is an option to undervolt a GPU specifically (pp_od_sclk_voltage isn't supported yet in our local builds so I can't see what it would look like). I'll have to take a look at the kernel code for that and see. I'll try to add the voltage OverDrive control to the SMI, but if the functionality isn't what you're looking for (not sure if you can only increase voltage or not), you can report it in the kernel project at https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver . If the functionality isn't in the kernel, the SMI can't do it. All the SMI does is make kernel calls via sysfs files.

**Comment by kentrussell** [comment]
I checked the kernel code, the option only exists to over-volt. If you want ROCm to introduce under-volting, make an issue report on the ROCK project at https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver . The SMI can't do anything that the kernel doesn't support, so the kernel needs to support it first.
