### ISSUE TITLE
How to set value back to default value 

### ISSUE THREAD

**Issue by Pacius** [RadeonOpenCompute/ROC-smi#34]
Such as fanspeed,clock

**Comment by kentrussell** [comment]
Refer to the README.md or use "rocm-smi --help" for a list of available commands, including how to reset:
https://github.com/RadeonOpenCompute/ROC-smi
OR
rocm-smi --help

  -r, --resetclocks            Reset sclk and mclk to default
 --resetfans                  Reset fans to automatic (driver) control
