### ISSUE TITLE
rocm-smi does not report GPU Utilization

### ISSUE THREAD

**Issue by colesdav** [RadeonOpenCompute/ROC-smi#37]
Hello, 

I am running Ubuntu 16.04 LTS on the following system: 
MB  = Asus Z97 Deluxe. 
CPU = i7-4790K
GPU1=  R9 Fury X. 
GPU 2= R9 Nano.
SSHD = Seagate 2 TB. 

I am running AMDGPU-PRO Drivers 18.10 with ROCm. 
I test rocm-smi and I note that there is now GPU Utilization report available. 

Please advise if GPU Utilization report will be added to rocm-smi. 

It looks like a new Linux kernel patch will be released to expose GPU usage information in future: "A patch has been submitted to expose GPU usage via Sysfs: https://lists.freedesktop.org/archives/amd-gfx/2018-June/023283.html It would likely appear in Linux 4.19.

Is this is related to the above problem? 

Thanks.

**Comment by kentrussell** [comment]
The SMI can only report what's supported by the kernel. If a feature is available in the kernel and is exposed via sysfs/debugfs, then the SMI can support it.

If there is GPU usage exposed by sysfs as the patch above implies, then once that patch is integrated into the ROCK (Radeon Open Compute Kernel), then we can add that to the SMI. But the kernel support needs to be there first, and it's not currently present in our kernel. Once it is, we will add it to the SMI
