### ISSUE TITLE
changing cpu frequency

### ISSUE THREAD

**Issue by trinayan** [RadeonOpenCompute/ROC-smi#4]
Is there a way to use this tool to change the CPU frequency on an APU. Or currently only the GPU is supported. ?

**Comment by trinayan** [comment]
On our carrizo board running rocm 1.4 when doing rocm-smi -a the supported GPU memory clock shows no options. Does it mean we cannot scale the memory frequency on carrizo currently? We need to be able to do it for our experiments.

**Comment by gstoner** [comment]
ROCm-SMI does not work with these function on Carrizo

greg
On Apr 17, 2017, at 1:46 PM, trinayan <notifications@github.com<mailto:notifications@github.com>> wrote:


On our carrizo board running rocm 1.4 when doing rocm-smi -a the supported GPU memory clock shows no options. Does it mean we cannot scale the memory frequency on carrizo currently? We need to be able to do it for our experiments.

**Comment by trinayan** [comment]
thanks for the info

**Comment by trinayan** [comment]
So I would be glad if you could tell me why rocm-smi doesnt support setting the memory frequency on carrizo. I mean I can change the files in sys/class/drm/device/ to support different memory clocks with the maximum set to the specifications of the chip and then use rocm-smi to set it to one of those levels.

Will this not work? I just want to know this before I do something fancy that damages the chip since we have only one of those.

**Comment by kentrussell** [comment]
Sorry for the late reply. For CZ, if the option is available, it will be now under the pp_dpm_mclk sysfs (rocm-smi -s will also show it, rocm-smi --setmclk to set it). This will display all supported memory frequencies. This was something that was recently implemented, so it should work now.
