### ISSUE TITLE
--setmemoverdrive does nothing

### ISSUE THREAD

**Issue by Macribit** [RadeonOpenCompute/ROC-smi#41]
hi in kernel 4.19 --setmemoverdrive 5 doesn't increase frequency of clocks

```
sudo ./rocm-smi --setmemoverdrive 5


====================    ROCm System Management Interface    ====================

          ******WARNING******

          Operating your AMD GPU outside of official AMD specifications or outside of
          factory settings, including but not limited to the conducting of overclocking
          (including use of this overclocking software, even if such software has been
          directly or indirectly provided by AMD or otherwise affiliated in any way
          with AMD), may cause damage to your AMD GPU, system components and/or result
          in system failure, as well as cause other problems. DAMAGES CAUSED BY USE OF
          YOUR AMD GPU OUTSIDE OF OFFICIAL AMD SPECIFICATIONS OR OUTSIDE OF FACTORY
          SETTINGS ARE NOT COVERED UNDER ANY AMD PRODUCT WARRANTY AND MAY NOT BE COVERED
          BY YOUR BOARD OR SYSTEM MANUFACTURER'S WARRANTY. Please use this utility with caution.
          
Do you accept these terms? [y/N] y
GPU[0]          : Successfully set GPU Memory OverDrive to 5%
GPU[0]          : Successfully set GPU Memory Clock frequency mask to Level 1
GPU[1]          : Successfully set GPU Memory OverDrive to 5%
GPU[1]          : Successfully set GPU Memory Clock frequency mask to Level 1
====================           End of ROCm SMI Log          ====================
```

clock stays the same 
```

Clock Gating Flags Mask: 0x3fbcf
        Graphics Medium Grain Clock Gating: On
        Graphics Medium Grain memory Light Sleep: On
        Graphics Coarse Grain Clock Gating: On
        Graphics Coarse Grain memory Light Sleep: On
        Graphics Coarse Grain Tree Shader Clock Gating: Off
        Graphics Coarse Grain Tree Shader Light Sleep: Off
        Graphics Command Processor Light Sleep: On
        Graphics Run List Controller Light Sleep: On
        Graphics 3D Coarse Grain Clock Gating: Off
        Graphics 3D Coarse Grain memory Light Sleep: Off
        Memory Controller Light Sleep: On
        Memory Controller Medium Grain Clock Gating: On
        System Direct Memory Access Light Sleep: Off
        System Direct Memory Access Medium Grain Clock Gating: On
        Bus Interface Medium Grain Clock Gating: Off
        Bus Interface Light Sleep: On
        Unified Video Decoder Medium Grain Clock Gating: On
        Video Compression Engine Medium Grain Clock Gating: On
        Host Data Path Light Sleep: On
        Host Data Path Medium Grain Clock Gating: On
        Digital Right Management Medium Grain Clock Gating: Off
        Digital Right Management Light Sleep: Off
        Rom Medium Grain Clock Gating: On
        Data Fabric Medium Grain Clock Gating: Off

GFX Clocks and Power:
        1750 MHz (MCLK)
        1104 MHz (SCLK)
        214 MHz (PSTATE_SCLK)
        300 MHz (PSTATE_MCLK)
        956 mV (VDDGFX) 
        39.155 W (average GPU)

GPU Temperature: 58 C
GPU Load: 100 %

UVD: Disabled


```

**Comment by kentrussell** [comment]
Does the dmesg say anything? What system are you running? Some systems don't support this (like APUs, since the GPU memory is technically system memory, or some older GPUs).

**Comment by Macribit** [comment]
2 x Rx 460 (it's happening on both), Gigabyte ab350 gaming rev 1.0, Ryzen 5 1600

dmesg says nothing.

**Comment by Macribit** [comment]
I think this bug has been reported upstream, it's not only roc smi that doesn't work but any other tool or just echoing that doesn't work.

https://bugs.freedesktop.org/show_bug.cgi?id=106177

**Comment by Macribit** [comment]
I think this bug has been reported upstream, it's not only roc smi that doesn't work but any other tool or just echoing that doesn't work.

https://bugs.freedesktop.org/show_bug.cgi?id=106177

**Comment by kentrussell** [comment]
Just as an update, I've got the confirmation here as well. Working on discussing with amdgpu regarding plans for how to address it.

**Comment by kentrussell** [comment]
They just posted a fix to the main amd-staging-drm-next branch at https://lists.freedesktop.org/archives/amd-gfx/2018-October/028099.html and https://lists.freedesktop.org/archives/amd-gfx/2018-October/028281.html . We'll try to get it into 1.9.2 but it might have to wait until 2.0

**Comment by firebird631** [comment]
Using amdgpu-pro (latest 18.40), ubuntu 18.04 (4.15.0-42-generic) with an RX480, when trying --setmemoverdrive it overdrive the core at maximum and did nothing on the memory.

**Comment by jlgreathouse** [comment]
Please note that this tracker is for issues with the ROCm software stack, not amdgpu-pro.

**Comment by jlgreathouse** [comment]
Looks like these changes made it into ROCm 2.0, but I don't think this fixed the problem that `--setmemoverdrive` doesn't actually work.

@kentrussell with the addition of `--setmlevel` as an option for directly modifying the MCLK tables, I'm wondering if we should instead just remove `--setmemoverdrive` as a feature in rocm-smi. IIRC, there were plans to deprecate the `pp_sclk_od` and `pp_mclk_od` features in deference to directly modifying the DPM tables with `pp_od_clk_voltage`. Since the memory overdrive feature doesn't appear to work in the driver anyway, we could remove it from `rocm-smi` and just say "use `--setmlevel`".

Thoughts?

**Comment by kentrussell** [comment]
Thats fine. I will take care of it on Friday

**Comment by kentrussell** [comment]
Closing the issue as this is a bug with the upstream kernel. If you want it addressed, you'll need to fill out a bug report with bugs.freedesktop.org for amdgfx to take a look at it. The file in question is pp_mclk_od , but I believe that they have deprecated support for this functionality in lieu of using the --setmlevel (which uses the pp_od_clk_voltage flag).

2.3 will explain this more fully
