### ISSUE TITLE
ECC info

### ISSUE THREAD

**Issue by XXLAI** [RadeonOpenCompute/ROC-smi#54]
how can we get ECC ram info on the roc-smi? I want to know if the radeon vii has the ecc or not.

**Comment by kentrussell** [comment]
It's hopefully going to be added for 2.3 or 2.4. The RAS (ECC) code was only recently added to the amdgpu kernel, so it won't make it into the ROCm kernel until 2.3, at which time we should have some basic support in the SMI for it as well

**Comment by kentrussell** [comment]
If you want an answer sooner than then, talk to your card manufacturer (Sapphire, etc), they'll know what's on the ASIC.

**Comment by kentrussell** [comment]
2.3 will have information for ECC/RAS available for displaying. It would be wise to contact the card manufacturer to ensure that it has ECC-capable VRAM on the ASIC though, otherwise you might end up chasing ghosts if the card doesn't actually have VRAM that supports ECC on it

**Comment by kentrussell** [comment]
In 2.3
