### ISSUE TITLE
Option to show current voltage

### ISSUE THREAD

**Issue by SandboChang** [RadeonOpenCompute/ROC-smi#58]
Hi,

With the command 
```
watch rocm-smi
```
I can see the temp/clkfreq/power consumption and so on, but it seems there isn't a way to see the current voltage yet. 
Recently I am trying to undervolt my Vega, `--setslevel SCLKLEVEL SCLK SVOLT` option seems to successfully set the P6/P7 to a reduced voltage and I could see a temperature drop. But it would be nice to see if the voltage is sitting at an expected level.

Would it be available at some point?

**Comment by jlgreathouse** [comment]
I'll leave the feature request for `rocm-smi` to @kentrussell . However, I will note that you can read the voltage of your AMD GPU (in millivolts) by reading the sysfs file `/sys/class/hwmon/hwmonN/in0_input`. N, in this case, can change depending on your GPU's number.

So if you have a single GPU, for instance, you could (for now) run the following to supplement the output of rocm-smi with a reading of the voltage:
`watch "rocm-smi; cat /sys/class/hwmon/hwmon0/in0_input"`

**Comment by kentrussell** [comment]
As always, I'll say it here: "watch rocm-smi" is a terrible thing to do. It's designed to be a user-friendly interface, not as an efficient system monitor (see https://github.com/RadeonOpenCompute/ROC-smi/issues/38 ) . I'd recommend only watching the fields that you want (use "watch rocm-smi -P -t -c" to only watch Power/Temperature/Clocks) . I'll see if we can get voltage into 2.3 .

**Comment by SandboChang** [comment]
Interesting, as I actually tried to do some crazy by doing watch -n 0.1 rocm-smi, which from #38 should have run into error, but it actually works very well even with the three cards I have. 

Yes, at the end I probably don’t need to watch everything, but the capability of watching voltage as I tune it will be great.

**Comment by kentrussell** [comment]
Also, I am adding a --showvoltage flag that will hopefully make it into 2.3 .

**Comment by kentrussell** [comment]
I missed the 2.3 cutoff, it's slated for 2.4

**Comment by kentrussell** [comment]
In 2.3 release
