### ISSUE TITLE
rocm-smi --setslevel doesn't work

### ISSUE THREAD

**Issue by hyc3z** [RadeonOpenCompute/ROC-smi#59]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Fedora 29 w kernel 4.20
- GCC/Compiler version (if compiling from source):8.2.1
- ROCm/MIOpen version:2.1.0
- GPU model and memory:Radeon RX Vega 56 / 8GiB HBM2 Hynix

**Describe the problem**
rocm-smi --setslevel doesn't work
************************************************
Do you accept these terms? [y/N] y
Unable to write to sysfs file /sys/class/drm/card0/device/pp_od_clk_voltage
************************************************
I tried to vim the file using root privilege, and I failed again.
Could you guys give an idea what's the possible problem?

**Comment by jlgreathouse** [comment]
Did you turn on OverDrive in the ppfeaturemask of your driver?

For instance, [the default ppfeaturemask in kernel 4.20](https://github.com/torvalds/linux/blob/v4.20/drivers/gpu/drm/amd/amdgpu/amdgpu_drv.c#L117) is `0xfffd3fff`. [Bit 14 is OverDrive](https://github.com/torvalds/linux/blob/v4.20/drivers/gpu/drm/amd/include/amd_shared.h#L114). So setting `amdgpu.ppfeaturemask=0xfffd7fff` on your grub boot line.

**Comment by hyc3z** [comment]
@jlgreathouse Thank you so much! I added amdgpu.ppfeaturemask=0xfffd7fff in grub.cfg and everything starts to work now.
