### ISSUE TITLE
--resetclocks 

### ISSUE THREAD

**Issue by newling** [RadeonOpenCompute/ROC-smi#6]
rocm-smi is working great for me, but I get a problem with 
`./rocm-smi -d0 --resetclocks` .

my terminal hangs, and on restart the message is "A stop job is running for session c1 ..."  

I followed the default ROCm 1.5 install. Let me know what experiments/logs you need if this is a real issue.

**Comment by gstoner** [comment]
ROCm-SMI is python script that talks to the SYSFS interface of the driver,   We need to know more about you GPU your using and system

Greg
On May 22, 2017, at 3:04 AM, James Newling <notifications@github.com<mailto:notifications@github.com>> wrote:


rocm-smi is working great for me, but I get a problem with
./rocm-smi -d0 --resetclocks .

my terminal hangs, and on restart the message is "A stop job is running for session c1 ..."

I followed the default ROCm 1.5 install. Let me know what experiments/logs you need if this is a real issue.

**Comment by newling** [comment]
clinfo
Board name:					 Fiji [Radeon R9 FURY / NANO Series]
Device Topology:				 PCI[ B#2, D#0, F#0 ]

uname -a
Linux goudurix11 4.9.0-kfd-compute-rocm-rel-1.5-76 #1 SMP Thu Apr 27 15:25:46 CDT 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kentrussell** [comment]
@newling , does the issue still occur with the ROCm 1.6 release? If so, can you attach a file with the following output, as well as whether you installed the binaries, or built the kernel yourself:

dmesg
rocm-smi -a

**Comment by newling** [comment]
@kentrussell , the issue does not occur with ROCm 1.6.

**Comment by kentrussell** [comment]
Perfect!
