### ISSUE TITLE
documentation for profile settings

### ISSUE THREAD

**Issue by hairetikos** [RadeonOpenCompute/ROC-smi#64]
i'm after some documentation for the profile values of Radeon VII (PD_Data_limit_c, etc)

is there already documentation or can we please get some?

thanks

**Comment by jlgreathouse** [comment]
This is a function within the main amdgpu driver, not rocm-smi specifically. I recommend checking on the [amdgpu mailing list](https://lists.freedesktop.org/mailman/listinfo/amd-gfx), as you're more likely to catch the developers who actually work on this particular piece of our drivers.
