### ISSUE TITLE
Use proper notation for temperature and frequency units

### ISSUE THREAD

**Issue by sarunasb** [RadeonOpenCompute/ROC-smi#71]
Please use proper SI/scientific notation for:
1) temperature degrees: °C, not lowercase c;
2) frequency in Hz: MHz, not Mhz.

**Comment by kentrussell** [comment]
That's a kernel issue, not an SMI issue:
https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/blob/master/drivers/gpu/drm/amd/powerplay/hwmgr/smu7_hwmgr.c#L4444

However, for degrees, I have cleaned that up internally (to be in 2.8). I'll see if I can get the cleanup for the kernel done as well, or get it assigned to someone who can.
