### ISSUE TITLE
Radeon VII Can't set clocks after using --setvc with overdrive

### ISSUE THREAD

**Issue by WannaBeOCer** [RadeonOpenCompute/ROC-smi#74]
After setting the cards voltage with --setvc and overclocking the clock/memory using overdrive I am unable to get --setsclk/--setmclk to work correctly. When I set the sclk and mclk after using --setvc, rocm-smi shows the core clock and memory clock as N/A and performance is lower than stock. 

--setvc works perfectly when keeping the clocks at stock. I see a large uplift in performance even compared to overclocking using overdrive.

--setsclk/--setmclk work correctly after using overdrive if I don't touch voltage when using --setvc. Performance is higher than stock but lower than setting the voltage since the card is power throttling even with a power target of 300w. Luckily these cards undervolt by a large amount.

**Comment by kentrussell** [comment]
What is the make+model of the Radeon VII? And is it using the stock VBIOS, or have you updated the VBIOS on there?

**Comment by WannaBeOCer** [comment]
I bought my Radeon VII directly from AMD's website on launch day. I'm not sure if new Radeon VIIs still ship without UEFI support but when I received mine the first week of release I updated it with the UEFI update AMD provided on their site.

Make: AMD 
Model: Radeon VII
Bios: 016.004.000.038.011717

**Comment by kentrussell** [comment]
Thanks for the confirmation. That's definitely not the expected result (setting voltage curve shouldn't override sclk/mclk), we're looking into it internally

**Comment by WannaBeOCer** [comment]
@kentrussell Just wanted to provide an update that this might of been a kernel bug that has been resolved. I haven't experienced this issue with kernel 5.3.8-5.3.11.

**Comment by kentrussell** [comment]
That's a positive at least. There were a couple patches that could have fixed it that I am looking at, so hopefully on the next release we'll be able to pull those in. Thanks for the update!

**Comment by kentrussell** [comment]
I'll close this for now, but re-open it if there are any issues with the newer releases.
