### ISSUE TITLE
Radeon VII --setmlevel broken

### ISSUE THREAD

**Issue by JMadgwick** [RadeonOpenCompute/ROC-smi#75]
The '--setmlevel' argument requires 3 parameters but the Radeon VII does not have adjustable memory voltage. To set manually works fine: `echo "m 1 1200" > /sys/class/drm/card0/device/pp_od_clk_voltage`
But this does not:
```
rocm-smi --setmlevel 1 1200
usage: rocm-smi [-h] [-d DEVICE [DEVICE ...]] [-i] [-v] [--showhw]
<<--snip-->>
rocm-smi: error: argument --setmlevel: expected 3 argument(s)
```
Giving 3 args results in:
```
Unable to write to sysfs file /sys/class/drm/card0/device/pp_od_clk_voltage
WARNING: IO or OS error
ERROR: GPU[0] 		: Unable to set mclk clock to Level m 1 1200 1000
WARNING: One or more commands failed
```
This is because internally the driver doesn't accept a voltage parameter for this GPU.

Ideally the command could print a message saying that the users voltage was ignored if they entered one and then set the clock, or just set the clock if they didn't ask for a voltage.
Right now it doesn't work at all. `--setslevel` is also still broken but I have made a comment on the existing issue for that as it's know already.

_I am using ROCm 2.9_

**Comment by kentrussell** [comment]
Sorry for the lateness, cleaning things up as we officially deprecate this repo and use the rocm_smi_lib project. This should have been resolved in ROCm 3.8. If not, please open a new issue at https://github.com/RadeonOpenCompute/rocm_smi_lib. Thank you!
