### ISSUE TITLE
Feature Request: Show CPU temps/readings

### ISSUE THREAD

**Issue by shimmervoid** [RadeonOpenCompute/ROC-smi#76]
Hello,

This may be a long shot request, can rocm-smi show cpu temps and/or related readings like voltages and such. If so, can they be adjusted? Also, I once remember rzyen cpu's enumerated under clinfo, and this is no longer the case. Exclusion for cpus? 

Thanks,

**Comment by kentrussell** [comment]
Unfortunately this will not be possible as the hwmon interface is different for these various chips, and it can't be controlled through the permissions set for GPUs. If you still want to see this pursued, please open a new issue at https://github.com/RadeonOpenCompute/rocm_smi_lib, as this repo will be deprecated and all SMI CLI functionality has moved over there. But it doesn't seem like it would be feasible for the SMI CLI as-is. Thank you!
