### ISSUE TITLE
Option to Set Fan Back to Auto

### ISSUE THREAD

**Issue by mathewhall** [RadeonOpenCompute/ROC-smi#8]
Currently there is no way to hand control of the fan speed back to the driver after setting it.  This can be done by writing a 2 to pwm1_enable, so it can be done manually, but it would be nice if there was a --resetfan option as part of ROC-smi.  If you think this is something worth upstreaming I can submit a pull request with the change.

**Comment by gstoner** [comment]
This would be great.. I why we open source the stack. ; )

Greg
On Jul 5, 2017, at 9:57 PM, mathewhall <notifications@github.com<mailto:notifications@github.com>> wrote:


Currently there is no way to hand control of the fan speed back to the driver after setting it. This can be done by writing a 2 to pwm1_enable, so it can be done manually, but it would be nice if there was a --resetfan option as part of ROC-smi. If you think this is something worth upstreaming I can submit a pull request with the change.
