### ISSUE TITLE
Ubuntu python dependency in Ubuntu 20.04 / python3 support

### ISSUE THREAD

**Issue by clemej** [RadeonOpenCompute/ROC-smi#83]
The upcoming Ubuntu 20.04 removes the `python` package, and won't ship with python2 by default.  

The upshot is that the debian control file for rocm-smi, as stands, is no longer installable on the upcoming ubuntu 20.04:

```
$ $ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu Focal Fossa (development branch)
Release:        20.04
Codename:       focal

$ sudo apt install rocm-smi
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 rocm-smi : Depends: python but it is not installable
E: Unable to correct problems, you have held broken packages.

$ cat /etc/apt/sources.list.d/rocm.list
deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ xenial main
$
```

The quick fix is to change the package dependency to `python2`, or if `rocm-smi` is python3 compatible, `python3`. (I admit I'm lazy and haven't checked if its python3 compatible already or not).

**Comment by clemej** [comment]
Looks like there's already a pull request for this #79 , although the fix of `python | python3` may or may not be sufficient.

**Comment by clemej** [comment]
Looks like rocm is python3 compatible already, so if you change python to python3 in the debian control file, and change `/usr/bin/env python` to `/usr/bin/env python3` at the top of the file, I don't see why it wouldn't work (the second change is necessary, as `/usr/bin/python` doesn't exist in 20.04).

**Comment by barf** [comment]
Can reproduce this on Ubuntu 20.04, also affected.

Changed the shebang to 'python3' and debian control file in #85 , hope this helps, the if statement seemed unnecessary in #79

**Comment by Danny3** [comment]
Any update on this ?

**Comment by kentrussell** [comment]
It'll be in the next release. Sorry for the delay
