### ISSUE TITLE
VRAM shows as N/A with rocm 3.3.0

### ISSUE THREAD

**Issue by elukey** [RadeonOpenCompute/ROC-smi#90]
Hi!

I am using rocm 3.3.0, and this is the output for my GPU (Vega 10 XT) of rocm-smi:

```
========================ROCm System Management Interface========================
================================================================================
GPU  Temp   AvgPwr  SCLK    MCLK    Fan    Perf  PwrCap  VRAM%  GPU%
1    25.0c  10.0W   852Mhz  167Mhz  14.9%  auto  170.0W  N/A    0%
================================================================================
==============================End of ROCm SMI Log ==============================
```

The interesting thing is that VRAM% is always N/A, meanwhile if I execute `radeontop` I can see correct values. 

I am running rocm on Debian 10 (Buster) with kernel 4.19.132. I can provide more details if needed!

**Comment by elukey** [comment]
With a debug print it seems that the `/sys/class/drm/card1/device/mem_busy_percent` path is not present on sysfs. The debug print that I added was between these two lines: https://github.com/RadeonOpenCompute/ROC-smi/blob/master/rocm_smi.py#L211-L212

**Comment by elukey** [comment]
@kentrussell Hi! I am wondering if you have an idea about this :)

**Comment by kentrussell** [comment]
It was a bug in the 3.3 release. If you use the 3.5 version of the SMI, it will be fixed. See https://github.com/RadeonOpenCompute/ROC-smi/commit/7b3a9f086103008f630e6ad12331b0659e8103dd . Thankfully the 3.5 SMI is just the Python file and can work with 3.3, you don't have to upgrade the entire ROCm stack to get this fix integrated

**Comment by elukey** [comment]
Thanks for the answer! From a quick check I think that the rocm-smi version that I am using has the commit that you mentioned, but I'll try 3.5 and report back!

**Comment by kentrussell** [comment]
If it still doesn't work, try add --log=DEBUG to see if it gives any additional helpful messages

**Comment by elukey** [comment]
If I add it with 3.3, I get:

```
elukey@stat1005:~$ sudo /opt/rocm/bin/rocm-smi --showmemuse --log=DEBUG


========================ROCm System Management Interface========================
================================================================================
ERROR: GPU[1] 		: Unable to get GPU memory use.
DEBUG: GPU[1]	: GPU memory usage not supported (file is empty)
================================================================================
==============================End of ROCm SMI Log ==============================
```

**Comment by kentrussell** [comment]
OK, this is where the terminology gets confusing/annoying (because I worded it wrong)
--showmemuse is for showing Memory Utilization, which is how "busy" the memory blocks are (100% would mean that the memory blocks on the card are constantly in use, regardless of how much VRAM it uses). I don't think VG10 supports that (I can check)

What you're looking for (amount of used memory) would be under "--showmeminfo vram" which shows the used/total VRAM. The rocm-smi (no-flags) option just does the math and takes used/total and reports it as a percentage

**Comment by elukey** [comment]
Thanks! I get a similar error though with showmeminfo:

```
elukey@stat1005:~$ sudo /opt/rocm/bin/rocm-smi --showmeminfo vram --log=DEBUG


========================ROCm System Management Interface========================
================================================================================
DEBUG: Unable to get vram_used
ERROR: GPU[1] 		: Unable to get vram memory usage information
================================================================================
==============================End of ROCm SMI Log ==============================
```

So I am wondering if my card/drivers support this, it seems that there is no info in sysfs..

**Comment by kentrussell** [comment]
Peculiar, it works on my Fiji+VG10 combo (FJ is older than VG10 so it should be fine):
$ cat /sys/class/drm/card*/device/mem_info_vram*
4294967296
70537216
unknown
17163091968
21704704
samsung

(That's total/used/vendor for VG10, then for FJ)
Can you attach your dmesg and maybe there's something helpful in there?

**Comment by elukey** [comment]
@kentrussell I can add my dmesg, but I also have to mention that we deploy ubuntu xenial packages on Debian 10 Buster. So far everything worked well, but I am wondering if there are differences in the way that /sys values are exposed.

**Comment by kentrussell** [comment]
There shouldn't be. The code is all pretty straight-forward:
        /* Add the two VRAM-related sysfs files */
        ret = sysfs_create_files(&adev->dev->kobj, amdgpu_vram_mgr_attributes);
        if (ret)
                DRM_ERROR("Failed to register sysfs\n");

https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/blob/master/drivers/gpu/drm/amd/amdgpu/amdgpu_vram_mgr.c#L161

There aren't any ASIC-specific or OS-specific checks, we just add the files in.

**Comment by elukey** [comment]
```
elukey@stat1005:~$ sudo dmesg | egrep 'drm|gpu|amd|kfd'
[    0.000000] Linux version 4.19.0-10-amd64 (debian-kernel@lists.debian.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 4.19.132-1 (2020-07-24)
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-4.19.0-10-amd64 root=UUID=f84f9ee9-a26a-4518-a896-0309339942f5 ro ixgbe.allow_unsupported_sfp=1 console=ttyS1,115200n8 elevator=deadline
[    0.474417] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.19.0-10-amd64 root=UUID=f84f9ee9-a26a-4518-a896-0309339942f5 ro ixgbe.allow_unsupported_sfp=1 console=ttyS1,115200n8 elevator=deadline
[    5.150865] pci 0000:06:00.1: quirk_gpu_hda+0x0/0x10 took 13669 usecs
[    6.816114] usb usb1: Manufacturer: Linux 4.19.0-10-amd64 ehci_hcd
[    6.943659] usb usb2: Manufacturer: Linux 4.19.0-10-amd64 ehci_hcd
[   21.354031] fbcon: mgadrmfb (fb0) is primary device
[   21.473713] mgag200 0000:0c:00.0: fb0: mgadrmfb frame buffer device
[   21.543894] [drm] amdgpu kernel modesetting enabled.
[   21.544360] [drm] Initialized mgag200 1.0.0 20110418 for 0000:0c:00.0 on minor 0
[   21.652247] kfd kfd: Initialized module
[   21.653538] amdgpu 0000:06:00.0: enabling device (0000 -> 0003)
[   21.653893] [drm] initializing kernel modesetting (VEGA10 0x1002:0x6861 0x1002:0x0C1E 0x00).
[   21.653949] [drm] register mmio base: 0x91C00000
[   21.653951] [drm] register mmio size: 524288
[   21.653972] [drm] add ip block number 0 <soc15_common>
[   21.653973] [drm] add ip block number 1 <gmc_v9_0>
[   21.653974] [drm] add ip block number 2 <vega10_ih>
[   21.653978] [drm] add ip block number 3 <psp>
[   21.653980] [drm] add ip block number 4 <powerplay>
[   21.653981] [drm] add ip block number 5 <dm>
[   21.653983] [drm] add ip block number 6 <gfx_v9_0>
[   21.653985] [drm] add ip block number 7 <sdma_v4_0>
[   21.653987] [drm] add ip block number 8 <uvd_v7_0>
[   21.653989] [drm] add ip block number 9 <vce_v4_0>
[   21.729064] amdgpu 0000:06:00.0: firmware: direct-loading firmware amdgpu/vega10_gpu_info.bin
[   21.729093] [drm] UVD(0) is enabled in VM mode
[   21.729095] [drm] UVD(0) ENC is enabled in VM mode
[   21.729097] [drm] VCE enabled in VM mode
[   22.978726] [drm] GPU posting now...
[   24.075963] [drm] vm size is 262144 GB, 4 levels, block size is 9-bit, fragment size is 9-bit
[   24.075978] amdgpu 0000:06:00.0: BAR 2: releasing [mem 0x3bff0000000-0x3bff01fffff 64bit pref]
[   24.075980] amdgpu 0000:06:00.0: BAR 0: releasing [mem 0x3bfe0000000-0x3bfefffffff 64bit pref]
[   24.076024] amdgpu 0000:06:00.0: BAR 0: assigned [mem 0x38000000000-0x383ffffffff 64bit pref]
[   24.076030] amdgpu 0000:06:00.0: BAR 2: assigned [mem 0x38400000000-0x384001fffff 64bit pref]
[   24.076082] amdgpu 0000:06:00.0: VRAM: 16368M 0x000000F400000000 - 0x000000F7FEFFFFFF (16368M used)
[   24.076083] amdgpu 0000:06:00.0: GART: 512M 0x000000F800000000 - 0x000000F81FFFFFFF
[   24.076087] [drm] Detected VRAM RAM=16368M, BAR=16384M
[   24.076088] [drm] RAM width 2048bits HBM
[   24.076169] [drm] amdgpu: 16368M of VRAM memory ready
[   24.076171] [drm] amdgpu: 16368M of GTT memory ready.
[   24.076182] [drm] GART: num cpu pages 131072, num gpu pages 131072
[   24.076255] [drm] PCIE GART of 512M enabled (table at 0x000000F400900000).
[   24.097472] amdgpu 0000:06:00.0: firmware: direct-loading firmware amdgpu/vega10_sos.bin
[   24.100345] amdgpu 0000:06:00.0: firmware: direct-loading firmware amdgpu/vega10_asd.bin
[   24.104302] amdgpu 0000:06:00.0: firmware: direct-loading firmware amdgpu/vega10_smc.bin
[   24.104643] amdgpu 0000:06:00.0: firmware: direct-loading firmware amdgpu/vega10_pfp.bin
[   24.104800] amdgpu 0000:06:00.0: firmware: direct-loading firmware amdgpu/vega10_me.bin
[   24.104919] amdgpu 0000:06:00.0: firmware: direct-loading firmware amdgpu/vega10_ce.bin
[   24.105073] amdgpu 0000:06:00.0: firmware: direct-loading firmware amdgpu/vega10_rlc.bin
[   24.105826] amdgpu 0000:06:00.0: firmware: direct-loading firmware amdgpu/vega10_mec.bin
[   24.116331] amdgpu 0000:06:00.0: firmware: direct-loading firmware amdgpu/vega10_mec2.bin
[   24.118379] amdgpu 0000:06:00.0: firmware: direct-loading firmware amdgpu/vega10_sdma.bin
[   24.128779] amdgpu 0000:06:00.0: firmware: direct-loading firmware amdgpu/vega10_sdma1.bin
[   24.128786] [drm] use_doorbell being set to: [true]
[   24.128967] [drm] use_doorbell being set to: [true]
[   24.130119] amdgpu 0000:06:00.0: firmware: direct-loading firmware amdgpu/vega10_uvd.bin
[   24.130125] [drm] Found UVD firmware Version: 1.87 Family ID: 17
[   24.130134] [drm] PSP loading UVD firmware
[   24.138148] amdgpu 0000:06:00.0: firmware: direct-loading firmware amdgpu/vega10_vce.bin
[   24.138155] [drm] Found VCE firmware Version: 55.3 Binary ID: 4
[   24.138170] [drm] PSP loading VCE firmware
[   24.475482] [drm] Display Core initialized with v3.1.59!
[   24.476669] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[   24.476670] [drm] Driver supports precise vblank timestamp query.
[   24.499626] [drm] UVD and UVD ENC initialized successfully.
[   24.599197] [drm] VCE initialized successfully.
[   24.614183] kfd kfd: Allocated 3969056 bytes on gart
[   24.614502] kfd kfd: added device 1002:6861
[   24.614801] [drm] Cannot find any crtc or sizes
[   24.614901] amdgpu 0000:06:00.0: ring 0(gfx) uses VM inv eng 4 on hub 0
[   24.614903] amdgpu 0000:06:00.0: ring 1(comp_1.0.0) uses VM inv eng 5 on hub 0
[   24.614904] amdgpu 0000:06:00.0: ring 2(comp_1.1.0) uses VM inv eng 6 on hub 0
[   24.614905] amdgpu 0000:06:00.0: ring 3(comp_1.2.0) uses VM inv eng 7 on hub 0
[   24.614906] amdgpu 0000:06:00.0: ring 4(comp_1.3.0) uses VM inv eng 8 on hub 0
[   24.614907] amdgpu 0000:06:00.0: ring 5(comp_1.0.1) uses VM inv eng 9 on hub 0
[   24.614908] amdgpu 0000:06:00.0: ring 6(comp_1.1.1) uses VM inv eng 10 on hub 0
[   24.614909] amdgpu 0000:06:00.0: ring 7(comp_1.2.1) uses VM inv eng 11 on hub 0
[   24.614910] amdgpu 0000:06:00.0: ring 8(comp_1.3.1) uses VM inv eng 12 on hub 0
[   24.614911] amdgpu 0000:06:00.0: ring 9(kiq_2.1.0) uses VM inv eng 13 on hub 0
[   24.614912] amdgpu 0000:06:00.0: ring 10(sdma0) uses VM inv eng 4 on hub 1
[   24.614913] amdgpu 0000:06:00.0: ring 11(sdma1) uses VM inv eng 5 on hub 1
[   24.614914] amdgpu 0000:06:00.0: ring 12(uvd<0>) uses VM inv eng 6 on hub 1
[   24.614914] amdgpu 0000:06:00.0: ring 13(uvd_enc0<0>) uses VM inv eng 7 on hub 1
[   24.614915] amdgpu 0000:06:00.0: ring 14(uvd_enc1<0>) uses VM inv eng 8 on hub 1
[   24.614916] amdgpu 0000:06:00.0: ring 15(vce0) uses VM inv eng 9 on hub 1
[   24.614917] amdgpu 0000:06:00.0: ring 16(vce1) uses VM inv eng 10 on hub 1
[   24.614918] amdgpu 0000:06:00.0: ring 17(vce2) uses VM inv eng 11 on hub 1
[   24.614948] [drm] ECC is active.
[   24.615702] [drm] Initialized amdgpu 3.27.0 20150101 for 0000:06:00.0 on minor 1
```

I tried to filter few things to avoid a big dmesg, lemme know if you need more.

**Comment by kentrussell** [comment]
That's super weird, no error hiding in there. I assume that the files are just empty/missing as well? It'd be nice if this was just an SMI bug and not a kernel bug. SMI bugs are far easier to fix :) Try this one out (the one I did above):
$ cat /sys/class/drm/card*/device/mem_info_vram*

**Comment by elukey** [comment]
ah wait another bit: I am using the drivers included in the linux kernel, not the ones shipped by the ROCm suite, so this could be the culprit (noticed your reference about the rock kernel drivers).

**Comment by elukey** [comment]
> cat /sys/class/drm/card*/device/mem_info_vram*

elukey@stat1005:~$ cat /sys/class/drm/card*/device/mem_info_vram*
cat: '/sys/class/drm/card*/device/mem_info_vram*': No such file or directory

**Comment by kentrussell** [comment]
So none of them showed up, but none of them threw an error either... I'd suggest opening a bug with the kernel, since those files definitely shouldn't be excluded in Debian, unless I am completely missing something. They'll be able to get things figured out pretty quickly though. https://gitlab.freedesktop.org/drm/amd/-/issues . Sorry that I can't get this solved immediately, but the open sourced guys are pretty diligent and quick to reply. Hopefully they'll get things squared away soon. Good luck!

EDIT: I just saw your comment about using the pure upstream kernel. That would do it. My patches weren't added until the 5.1 kernel. Sorry about the confusion and back-and-forth there, I should've checked

**Comment by elukey** [comment]
So looking into the GH tags for https://github.com/torvalds/linux/commit/55c374e9eb72be0de5d4fe2ef4d7803cd4ea6329 it seems that the kernel 5.x includes the sysfs file creation for the VRAM, that would explain why I am not seeing neither errors nor the files that we expect..

**Comment by kentrussell** [comment]
That would do it. Sorry for not confirming that, it could've saved a few e-mail notifications :) At least we got down to the bottom of this

**Comment by elukey** [comment]
Nono the opposite, thanks a lot for all your time spent on this :) I am going to close this issue for the moment, and will report back when/if I'll be able to test on 5.x!
