### ISSUE TITLE
Incorrect variable naming in rocm-smi, crashing the setClockRange function!

### ISSUE THREAD

**Issue by sabbaghm** [RadeonOpenCompute/ROC-smi#92]
`clkType `or `clktype`!

There is a mistake in this script, breaking the setClockRange function.

All of `rocm-smi,` have this as `clktype ` (lower case **t**), only in this function we suddenly see three uses of `clkType ` (while the function argument is correctly named `clktype`). 

https://github.com/RadeonOpenCompute/ROC-smi/blob/08ebdddbbd25b40d385b4b25876cca9727bfd033/rocm_smi.py#L2460

Overall, I think the new rocm3.8 is very messy, especially with regards to `rocm-smi` and the compatible kernel versions. Please revamp it and make it work smoothly like rocm3.5 or earlier... with better guidelines to use it. Lot's of people are observing issues with the new version of ROCM, if you look at the issues. Thanks.

**Comment by kentrussell** [comment]
This was resolved during the transition of the SMI CLI from this repository to the LIB-backed rocm_smi_lib repository. If you have any issues, please open a new issue at https://github.com/RadeonOpenCompute/rocm_smi_lib, as this repo will be deprecated and all SMI CLI functionality has moved over there. Thank you!
