### ISSUE TITLE
division by zero on APU 4700u

### ISSUE THREAD

**Issue by ye-luo** [RadeonOpenCompute/ROC-smi#93]
Please cover APU in your test. It was fine in 3.8 but I got the following in 3.9
```
Traceback (most recent call last):
  File "/opt/rocm/bin/rocm-smi", line 2537, in <module>
    showAllConcise(deviceList)
  File "/opt/rocm/bin/rocm-smi", line 1058, in showAllConcise
    (fanLevel, fanSpeed) = getFanSpeed(device)
  File "/opt/rocm/bin/rocm-smi", line 182, in getFanSpeed
    return (fl, round((float(fl) / float(fm)) * 100, 2))
ZeroDivisionError: float division by zero
```

**Comment by kentrussell** [comment]
Thanks, this issue will be resolved in ROCm 4.1.  If not, please open a new issue at https://github.com/RadeonOpenCompute/rocm_smi_lib, as this repo will be deprecated and all SMI CLI functionality will be moving over there. Thank you!
