### ISSUE TITLE
More clearly indicate/explain deprecation

### ISSUE THREAD

**Issue by musicinmybrain** [RadeonOpenCompute/ROC-smi#94]
The last two commits, e39c0e2e and 164f5aca, renamed the only actual source file (`rocm_smi.py`) to `rocm_smi_deprecated.py` in the deb and rpm packages. That was also the main change in the most recent release.

It is not obvious, or even easy to find out, what exactly is deprecated and whether this repository represents a dead project. Based on a comment in https://github.com/RadeonOpenCompute/rocm_smi_lib/blob/master/python_smi_tools/rocmSmiLib_cli.py, that tool is supposed to replace this project.

It would be very helpful if the README.md could be updated to communicate this plan, and dissuade new users from adopting this project.

**Comment by kentrussell** [comment]
This will be done in 4.1. The intention was to have this pushed out a few releases ago, but it took some time to demangle things, as a large number of ROCm components were using the SMI CLI, so we couldn't officially deprecate things. But we look to finally have this done in 4.1. Thanks for your patience!
